name: Add Cloud Native Catalog Items
jobs:
  UpdateCloudNativeCatalog:
    runs-on: ubuntu-22.04
    outputs:
      contentID: ${{ steps.update_catalog_patterns.outputs.contentID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Set env
        run : |
          echo "MESHERY_CLOUD_BASE_URL=https://meshery.layer5.io" >> $GITHUB_ENV
          echo "MESHERY_CATALOG_FILES_DIR=catalog" >> $GITHUB_ENV
      - name: Cleanup
        run: |
          find $MESHERY_CATALOG_FILES_DIR ! -name 'index.html' ! -name 'artifacthub-repo.yml' -maxdepth 1 -type f -delete
          cd ./collections/_catalog
          for dir in */; do find $dir -maxdepth 1 -type f -delete; done
          cd ../../
      - id: update_catalog_patterns
        name: Update Catalog Patterns in Go
        run: |
          cd temp/scripts
          go run package.go
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}