name: Add Cloud Native Catalog Items
on: push
jobs:
  UpdateCloudNativeCatalog:
    runs-on: ubuntu-22.04
    outputs:
      contentID: ${{ steps.update_catalog_patterns.outputs.contentID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Set env
        run : |
          echo "MESHERY_CLOUD_BASE_URL=https://meshery.layer5.io" >> $GITHUB_ENV
          echo "MESHERY_CATALOG_FILES_DIR=catalog" >> $GITHUB_ENV
      - id: update_catalog_patterns
        name: Update Catalog Patterns in Go
        run: |
          cd temp/scripts
          patternId=$(go run package.go)
          echo "patternId=$patternId" >> $GITHUB_OUTPUT
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Print
        run: |
          echo "Pattern ID: ${{ steps.update_catalog_patterns.outputs.patternId }}"
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update catalog patterns"
          git push
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}